name: variant_analysis_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11      # For compatiblity with the multiqc especially on the HPC 
  - sra-tools        # For downloading FASTQ files (fastq-dump)
  - fastqc           # For quality control
  - multiqc          # For merging QC reports
  - bwa              # For genome alignment
  - samtools         # For BAM manipulation
  - bcftools         # For variant calling and VCF manipulation
  - snpeff           # For variant annotation
  - wget             # For downloading reference files
  - pigz             # For parallel compression (speeds up handling)
  - bbmap            # For paired-end read synchronization
  - snpsift          # For filter, manipulate, and annotate genomic functional variants in VCF files
